### ISSUE TITLE
Use current machine identity

### ISSUE THREAD

**Issue by allexivan** [fegmorte/aws-ecs-exec-command-cli#1]
I am using it in an AWS cloud shell and also on an ec2 instance which has identities attached to it, but it still asks for aws credentials files.
Can be these detected automatically?

**Comment by fegmorte** [comment]
Hi, 
For the moment I only check and force the lookup of an aws credentials file. But it is a good idea to let the choice if the command is executed directly on an EC2 instance. Boto3 will automatically try to load credentials from the instance metadata service and retrieve the IAM credentials attached to this instance.
I am going to add this change.
Thank you

**Comment by fegmorte** [comment]
hi @allexivan 

I have just pushed a new version of ecs_connect tool.
I added the ability to retrieve EC2 instance metadata to connect to ECS.
Be sure the IAM role attached to the EC2 instance grants the access to ECS with a policy like AmazonECS_FullAccess or something else that limiting the scope of the cluster you want to reach.
Feel free to try it.

Thanks for your help 👍 

Fred
